name: Build and Deploy Infrastructure and Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY_NAME: jorgeappacr
  IMAGE_BASE_NAME: python-flask-app
  REGISTRY_LOGIN_SERVER: jorgeappacr.azurecr.io
  APP_SERVICE_NAME: jorgeapp-app
  KEY_VAULT_NAME: jorgeappkv
  KEY_VAULT_SECRET_NAME_ACR_USERNAME: acr-username
  KEY_VAULT_SECRET_NAME_ACR_PASSWORD: acr-password1

jobs:
  build-bicep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1.0.7
        with:
          inlineScript: |
            az version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Bicep Templates
        run: |
          az bicep build --file modules/key-vault.bicep
          az bicep build --file main.bicep

  deploy-infrastructure:
    runs-on: ubuntu-latest
    needs: build-bicep
    outputs:
      acr_username: ${{ steps.deploy.outputs.acr_username }}
      acr_password: ${{ steps.deploy.outputs.acr_password }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure CLI
        uses: azure/cli@v1.0.7
        with:
          inlineScript: |
            az version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Purge existing Key Vault
        run: |
          az keyvault purge --name ${{ env.KEY_VAULT_NAME }} || true
          # Wait a bit for the purge to complete
          sleep 30

      - name: Deploy Bicep Templates
        id: deploy
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          DEPLOYMENT_OUTPUT=$(az deployment group create \
            --resource-group BCSAI2024-DEVOPS-STUDENTS-A-DEV \
            --name "main-${TIMESTAMP}" \
            --template-file main.bicep \
            --parameters main.parameters.json \
            --query properties.outputs)
          
          # Extract and mask sensitive outputs
          ACR_USERNAME=$(echo $DEPLOYMENT_OUTPUT | jq -r '.adminUserName.value')
          ACR_PASSWORD=$(echo $DEPLOYMENT_OUTPUT | jq -r '.adminPassword.value')
          echo "::add-mask::$ACR_PASSWORD"
          
          # Set outputs for next jobs
          echo "acr_username=$ACR_USERNAME" >> $GITHUB_OUTPUT
          echo "acr_password=$ACR_PASSWORD" >> $GITHUB_OUTPUT

  build-and-push-container:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
          username: ${{ needs.deploy-infrastructure.outputs.acr_username }}
          password: ${{ needs.deploy-infrastructure.outputs.acr_password }}

      - name: Set image version
        id: image-version
        run: echo "::set-output name=version::$(echo ${GITHUB_REF#refs/heads/})-$(date +'%Y.%m.%d.%H.%M')"

      - name: Build and push image
        working-directory: .
        run: |
          docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
          docker build . -t ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ github.ref_name }}-latest
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ steps.image-version.outputs.version }}
          docker push ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ github.ref_name }}-latest

  deploy-container:
    needs: build-and-push-container
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_SERVICE_NAME }}
          images: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_BASE_NAME }}:${{ github.ref_name }}-latest